//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSales
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RPDBSupermarketEntities1 : DbContext
    {
        public RPDBSupermarketEntities1()
            : base("name=RPDBSupermarketEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbAdjustment> tbAdjustments { get; set; }
        public DbSet<tbBrand> tbBrands { get; set; }
        public DbSet<tbCancel> tbCancels { get; set; }
        public DbSet<tbCart> tbCarts { get; set; }
        public DbSet<tbCategory> tbCategories { get; set; }
        public DbSet<tbProduct> tbProducts { get; set; }
        public DbSet<tbStockIn> tbStockIns { get; set; }
        public DbSet<tbSupplier> tbSuppliers { get; set; }
        public DbSet<tbUser> tbUsers { get; set; }
        public DbSet<tbStore> tbStores { get; set; }
    }
}
