//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSales
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAdjustment
    {
        public int id { get; set; }
        public string referenceno { get; set; }
        public string pcode { get; set; }
        public Nullable<int> qty { get; set; }
        public string action { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> sdate { get; set; }
        public string user { get; set; }
    }
}
