//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSales
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBrand
    {
        public tbBrand()
        {
            this.tbProducts = new HashSet<tbProduct>();
        }
    
        public int id { get; set; }
        public string brand { get; set; }
    
        public virtual ICollection<tbProduct> tbProducts { get; set; }
    }
}
