//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSales
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProduct
    {
        public tbProduct()
        {
            this.tbCarts = new HashSet<tbCart>();
            this.tbStockIns = new HashSet<tbStockIn>();
        }
    
        public string pcode { get; set; }
        public string barcode { get; set; }
        public string pdesc { get; set; }
        public int bid { get; set; }
        public int cid { get; set; }
        public decimal price { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<int> reorder { get; set; }
    
        public virtual tbBrand tbBrand { get; set; }
        public virtual ICollection<tbCart> tbCarts { get; set; }
        public virtual ICollection<tbStockIn> tbStockIns { get; set; }
    }
}
