//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSales
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSupplier
    {
        public tbSupplier()
        {
            this.tbStockIns = new HashSet<tbStockIn>();
        }
    
        public int id { get; set; }
        public string supplier { get; set; }
        public string address { get; set; }
        public string contactperson { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string fax { get; set; }
    
        public virtual ICollection<tbStockIn> tbStockIns { get; set; }
    }
}
